<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="laser_offset_x" value="0.115"/>
  <xacro:property name="laser_offset_z" value="0.01"/>
  <xacro:property name="laser_radius" value="0.035"/>
  <xacro:property name="laser_thickness" value="0.055"/>

  <joint name="laser_joint" type="fixed">
    <parent link="chassis" />
    <child link="laser_frame" />
    <origin xyz="${laser_offset_x} 0 ${chassis_height+laser_thickness/2}" rpy="0 0 0" />
  </joint>

  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 ${-laser_offset_z}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_thickness}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_thickness}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.3" radius="${laser_radius}" length="${laser_thickness}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>
  <gazebo reference="laser_frame">
    <material>Gazebo/Black</material>

    <sensor name="laser" type="ray">
      <pose> 0 0 0 0 0 0 </pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan> 
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>--ros-args --remap ~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</robot>
